1.1.3
antonKsanfTasks/Task-1_fork pull request #2
Opened 2023-09-25 12:08 UTC by antonksanf

PP Task 1.1.3 JDBC

2023-09-25 13:10 UTC, pdasilem requested changes

2023-09-25 13:10 UTC, pdasilem commented on src/main/java/jm/task/core/jdbc/dao/UserDaoJDBCImpl.java
> +            Statement statement = openConnection().createStatement();
используй ресурсы для автозакрытия

2023-09-25 13:10 UTC, pdasilem commented on src/main/java/jm/task/core/jdbc/util/Util.java
> +    private static Connection connection;
нет, не должны быть статик коннекшн. он в каждом методе должен инициализироваться

2023-09-25 13:10 UTC, pdasilem commented on src/main/java/jm/task/core/jdbc/util/Util.java
> +            throw new RuntimeException();
это здесь зачем?

2023-09-25 13:10 UTC, pdasilem commented on src/main/java/jm/task/core/jdbc/dao/UserDaoJDBCImpl.java
> +            closeConnection();
опен/клоз статик - такое себе удовольствие

2023-09-25 14:25 UTC, antonksanf commented on src/main/java/jm/task/core/jdbc/dao/UserDaoJDBCImpl.java
> +            Statement statement = openConnection().createStatement();
Исправил

2023-09-25 14:25 UTC, antonksanf commented on src/main/java/jm/task/core/jdbc/util/Util.java
> +    private static Connection connection;
Исправил

2023-09-26 09:47 UTC, pdasilem requested changes
убрать лишние файлы/папки из пр

2023-09-26 09:47 UTC, pdasilem commented on src/main/java/jm/task/core/jdbc/dao/UserDaoJDBCImpl.java
> +            throw new RuntimeException(e);
зачем выбрасываешь исключения в блоке кэтч?

2023-09-26 09:47 UTC, pdasilem commented on src/main/java/jm/task/core/jdbc/util/Util.java
> +        Connection connection = DriverManager.getConnection(dbURL);
конекшн должен инициализироваться в дао

2023-09-26 09:47 UTC, pdasilem commented on src/main/java/jm/task/core/jdbc/util/Util.java
> +    public static void closeConnection() throws SQLException {
этот метод здесь не нужен. автозакрытие в дао

2023-09-27 15:38 UTC, antonksanf commented on src/main/java/jm/task/core/jdbc/util/Util.java
> +    public static void closeConnection() throws SQLException {
Автозакрытие реализуется через try-with-recources

2023-09-27 15:39 UTC, antonksanf commented on src/main/java/jm/task/core/jdbc/util/Util.java
> +        Connection connection = DriverManager.getConnection(dbURL);
Исправил

2023-09-28 10:35 UTC, antonksanf commented on src/main/java/jm/task/core/jdbc/dao/UserDaoJDBCImpl.java
> +            Statement statement = openConnection().createStatement();
Исправил

2023-09-28 10:35 UTC, antonksanf commented
Я думал что удалил файлы добавив их в гитигнор, но оказалось, конечно же, что надо пользоваться "git rm --cached" и пушить новый коммит

2023-09-28 12:09 UTC, pdasilem approved these changes
на будущее. не буду проверять, пока не запросишь на ревью в гит. )

2023-09-28 13:20 UTC, merged